# Generated by Django 4.1.5 on 2023-02-01 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StandardDetails',
            fields=[
                ('standard_id', models.AutoField(primary_key=True, serialize=False)),
                ('standard', models.CharField(max_length=15)),
                ('sections', models.JSONField(default=['A', 'B'])),
                ('subjects', models.JSONField()),
                ('standard_created_on', models.DateField(auto_now_add=True)),
                ('standard_updated_on', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'standard_details',
            },
        ),
        migrations.CreateModel(
            name='StudentBasicDetails',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_enrollment', models.CharField(max_length=100, unique=True)),
                ('student_first_name', models.CharField(error_messages='', max_length=30)),
                ('student_last_name', models.CharField(default='', error_messages='', max_length=30)),
                ('student_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('T', 'TransGender'), ('N', 'NotToDisclose')], default='N', max_length=1)),
                ('student_DOB', models.DateField()),
                ('student_section', models.CharField(max_length=2)),
                ('student_enrolled', models.BooleanField(default=True)),
                ('student_class', models.CharField(choices=[], max_length=15)),
                ('student_enrollment_date', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'student_basic_details',
            },
        ),
        migrations.CreateModel(
            name='StudentParentsDetails',
            fields=[
                ('student_parent_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_parent_name', models.CharField(max_length=100)),
                ('student_parent_relation', models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Sibling', 'Sibling'), ('GrandParents', 'GrandParents')], max_length=15)),
                ('student_parent_created_date', models.DateField(auto_now_add=True)),
                ('student_parent_updated_date', models.DateField(auto_now=True)),
                ('student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='studentDetails.studentbasicdetails')),
            ],
            options={
                'db_table': 'student_parents_details',
            },
        ),
        migrations.CreateModel(
            name='StudentContactDetails',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_mob_no', models.BigIntegerField()),
                ('contact_alternate_mob_no', models.BigIntegerField(blank=True, null=True)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_alternate_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_created_date', models.DateField(auto_now_add=True)),
                ('contact_updated_date', models.DateField(auto_now=True)),
                ('student_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='studentDetails.studentbasicdetails')),
            ],
            options={
                'db_table': 'student_contact_details',
            },
        ),
    ]
