# Generated by Django 4.1.5 on 2023-02-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentDetails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentbasicdetails',
            name='student_enrollment_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='studentbasicdetails',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
