# Generated by Django 4.1.5 on 2023-02-11 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentDetails', '0002_alter_studentbasicdetails_student_enrollment_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentparentsdetails',
            unique_together={('student_parent_name', 'student_id', 'student_parent_relation')},
        ),
    ]
